### ISSUE TITLE
актуалізувати склад Чернівецької обласної ради

### ISSUE THREAD

**Issue by GS-0001** [ivkil/MC-Declarations#2]
- [ ] Вже не є депутатами (їх потрібно **забрати з актуального списку**):
1. Андрюк Михайло Іванович
2. Ванзуряк Роман Степанович
3. Коблюк Георгій Степанович
4. Козак Василь Васильович
5. Корчевий Віталій Євгенович
6. Собко Микола Степанович
7. Чукля Віктор Михайлович

- [ ] Є актуальними депутатами згідно http://oblrada.cv.ua/structure/deputies/ (їх **потрібно додати**):
1. Апостолюк Іван Васильович
2. Мартинюк Тетяна Іванівна
3. Субота Василь Йосипович
4. Сухар Анатолій Іванович
5. Ткачук Віталій Васильович
6. Чубрей Сергій Вікторович

**Comment by ivkil** [comment]
Fixed.
